description: run
 
target:
  service: singularity
  name: palisades33
  workspace_name: azmlws2igshare
 
environment:
  image: amlt-sing/acpt-torch2.7.1-py3.10-cuda12.6-ubuntu22.04
  # registry: azmlws2igshare.azurecr.io
 
storage:
  output:
    storage_account_name: igshare
    container_name: zelonglv
    mount_dir: /mnt/blob
 
code:
  local_dir: $CONFIG_DIR
 
jobs:
- name: aether
  priority: high
  preemptible: False
  identity: managed
  sku: NDv4:1xG1
  command:
    - bash run.sh
    
  submit_args:
    env:
      {SHARED_MEMORY_PERCENT: 1, MKL_THREADING_LAYER: GNU, _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/bcbec19e-5aea-46ab-8dad-17b0e68de117/resourceGroups/managed_idenity/providers/Microsoft.ManagedIdentity/userAssignedIdentities/igsharemi}